### ISSUE TITLE
fuckit with logging errors

### ISSUE THREAD

**Issue by Hnasar** [ajalt/fuckitpy#17] opened 2014-02-26 19:38 UTC
I'd very much like to use fuckitpy in a project I'm working on, but I don't want to silence errors (just proceed past them).
I don't think the current API supports this use case, but this fact is preventing me from using it.

**Comment by larkin** [comment] 2015-02-03 21:55
I'd love it to print stack traces too: sometimes you write a bunch of code and there's a few small errors -- expect a boolean and get a string, key errors, etc -- and running through the code once with fuckit and getting all the errors in the first pass would be faster than fixing one error at a time and rerunning it.

Finding a questionably legitimate use for fuckit.py would make my day.

**Comment by ajalt** [comment] 2015-02-04 00:27
Thanks for the input! I looked into this issue when it was first opened. Here's where I got:

It's totally possible to print a stack trace for the first SyntaxError in each module. Those are silenced by essentially deleting the offending source line. That usually creates more syntax errors which weren't present in the original code, and we don't want to see those.

For runtime errors, I unfortunately couldn't find a satisfactory solution. The problem is that once you use `fuckit(fuckit('module'))` (a.k.a. "double-fucking"), the module code that is executed isn't the original code at all. It's dynamically generated code that doesn't have any file information associated with it, and with a call stack that is completely different from the original. So for most errors, I could print the type of error, but no traceback.

I tried a few different ways to retain the original traceback, but I haven't found one that works in all cases.

I welcome any suggestions.

**Comment by pcurry** [comment] 2015-02-04 14:38
As predictable as this is, I suggest with regard to this problem, fuckit. :-)

**Comment by floer32** [comment] 2015-04-08 18:17
this thread is great. this module is so funny.

@Hnasar  if you _actually_ want to do this easily, without using a funny module, give `funcy` decorators a shot. You can use the [debug decorators](http://funcy.readthedocs.org/en/stable/debug.html) such as `@log_errors`, plus  [`@silent` or `@ignore`](http://funcy.readthedocs.org/en/latest/flow.html). These are very useful during development, especially with weird code. Strongly advised to remove them before going to production though 😅 

**Update:**

> Oh, I recommend anyone stumbling upon this funny thread... to legitimately check out `PySnooper` - it is not for steamrolling errors, but it is related to the general question of WTF IS THIS CODE DOING. :) basically traces what's going on
> 
> https://github.com/cool-RR/PySnooper

**Comment by GalenBusch** [comment] 2019-06-10 08:07
I had the greatest laugh reading the README and the FuckIt module. Steamroll errors. Fuck logging. Import *some* of whatever_shitty_module. I think I landed on this after spending 3 hours taking all of the Try/Except/Pass's out of my code and implementing logging.

For any poor soul that lands on this in the vein of logging; here you go.
```
from datetime import datetime
import sys
import inspect
def log(exception, function_name_string, arg3=''):
    callerframerecord = inspect.stack()[1]
    frame = callerframerecord[0]
    info = inspect.getframeinfo(frame)
    f=open("T:\\ype\\your\\fucking\\log\\path\\here\\and\\dont\\forget\\the.txt","a")
    t = datetime.now().strftime('%D %r')
    n = str(sys.argv[0])
    l = str(info.lineno)
    func = str(function_name_string)
    e = str(exception)
    a3 = str(arg3)
    log_entry = str('\n'+t+' | '+n+' | '+func+' | Line '+l+' | '+e+' | '+a3)
    f.write(log_entry)
    f.close
```
Example integrated into an except:
```
except Exception as e:
    log(e,'insert_into_database', pipe.return_query())
    pass
```
Go fix your fucking code.

**Closed** 2019-06-16 14:04 UTC

**Comment by floer32** [comment] 2019-06-17 16:53
Oh, I recommend anyone stumbling upon this funny thread... to legitimately check out `PySnooper` - it is not for steamrolling errors, but it is related to the general question of WTF IS THIS CODE DOING. :) basically traces what's going on

https://github.com/cool-RR/PySnooper
